package eu.kanade.presentation.theme.colorscheme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

internal object EtsumeColorScheme : BaseColorScheme() {

    override val darkScheme = darkColorScheme(
        primary = Color(0xFF77AAFF),
        onPrimary = Color(0xFF091325),
        primaryContainer = Color(0xFF224A9A),
        onPrimaryContainer = Color(0xFFE7F0FF),
        inversePrimary = Color(0xFF8DB8FF),
        secondary = Color(0xFFA47CFF),
        onSecondary = Color(0xFF180D2F),
        secondaryContainer = Color(0xFF332056),
        onSecondaryContainer = Color(0xFFF0E8FF),
        tertiary = Color(0xFF6E6BFF),
        onTertiary = Color(0xFFF1F0FF),
        tertiaryContainer = Color(0xFF29256A),
        onTertiaryContainer = Color(0xFFE5E4FF),
        background = Color(0xFF091120),
        onBackground = Color(0xFFEAF0FF),
        surface = Color(0xFF0F1728),
        onSurface = Color(0xFFEAF0FF),
        surfaceVariant = Color(0xFF141D31),
        onSurfaceVariant = Color(0xFFBEC7DE),
        surfaceTint = Color(0xFF77AAFF),
        inverseSurface = Color(0xFFE6ECFA),
        inverseOnSurface = Color(0xFF131A2C),
        error = Color(0xFFFFB4B4),
        onError = Color(0xFF5B1114),
        errorContainer = Color(0xFF7A1D22),
        onErrorContainer = Color(0xFFFFD9D8),
        outline = Color(0xFF58637E),
        outlineVariant = Color(0xFF263046),
        surfaceContainerLowest = Color(0xFF08101D),
        surfaceContainerLow = Color(0xFF0D1525),
        surfaceContainer = Color(0xFF111A2D),
        surfaceContainerHigh = Color(0xFF162137),
        surfaceContainerHighest = Color(0xFF1C2843),
    )

    override val lightScheme = lightColorScheme(
        primary = Color(0xFF365FE0),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFDCE5FF),
        onPrimaryContainer = Color(0xFF00195F),
        inversePrimary = Color(0xFFB6C7FF),
        secondary = Color(0xFF7D56D6),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFE8DEFF),
        onSecondaryContainer = Color(0xFF2B0C67),
        tertiary = Color(0xFF4E54C8),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFE0E2FF),
        onTertiaryContainer = Color(0xFF10195E),
        background = Color(0xFFF6F8FF),
        onBackground = Color(0xFF141B2F),
        surface = Color(0xFFF7F8FF),
        onSurface = Color(0xFF141B2F),
        surfaceVariant = Color(0xFFE9ECF8),
        onSurfaceVariant = Color(0xFF454D67),
        surfaceTint = Color(0xFF365FE0),
        inverseSurface = Color(0xFF252D42),
        inverseOnSurface = Color(0xFFF0F3FF),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        outline = Color(0xFF707A96),
        outlineVariant = Color(0xFFC6CADE),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF2F4FF),
        surfaceContainer = Color(0xFFEAEFFC),
        surfaceContainerHigh = Color(0xFFE1E6F6),
        surfaceContainerHighest = Color(0xFFD8DFF1),
    )
}
